name: ogprofiler
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pip
  - pyarrow>=15
  - pyyaml>=6
  - numpy>=1.26
  - scipy>=1.12
  - python-igraph>=0.11
  - leidenalg>=0.10
  - ete3>=3.1
  - progressbar2>=4
  - biopython>=1.83
  - psutil>=5.9
  - pytest>=8
  - ruff>=0.5
  - mypy>=1.10
  - types-pyyaml
  - diamond>=2
  - mmseqs2>=15
  - blast>=2.16
  - mafft>=7.5
  - fasttree>=2.1

